apps/animalshelter/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

## For now, putting our admin site modifications here
admin.site.site_header = "Animal Shelter Web Management"

urlpatterns = [
    path("", include("frontpage.urls")),
    path("admin/", admin.site.urls),
    path("listing/", include("listing.urls")),
    path("news/", include("news.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/listing/urls.py
## Zander B. Wells <zbwells@protonmail.com>
## Part of the Wise Animal Shelter Management System Project.
##
## Released under the terms of the MIT License.
## See LICENSE for details.

# File to contain all of the urls for the animal listings.

from django.urls import path
from . import views

urlpatterns = [
        path("", views.IndexView.as_view(), name="index"),
        path("<int:pk>/", views.DetailView.as_view(), name="detail"),
        path("extra/<int:pk>/", views.ExtraView.as_view(), name="extra"),
]

apps/news/urls.py
## Amber Shackleford.
## Part of the Wise Animal Shelter Management System Project.
##
## Released under the terms of the MIT License.
## See LICENSE for details.

from django.urls import path 
from . import views

urlpatterns = [
	path("", views.News.as_view(), name = "news"),
]

apps/listing/models.py
## Zander B. Wells <zbwells@protonmail.com>
## Part of the Wise Animal Shelter Management System Project.
##
## Released under the terms of the MIT License.
## See LICENSE for details.

from django.db import models

## Models for the animal listing

'''
Animal model; contains all of the information for one animal.
Name, ID, Image, Species, Breed, Sex, Weight, 
Estimated Date of Birth, Intake date, Available on, 
Status, and other miscellaneous details.
'''

class Animal(models.Model):
    name = models.CharField(max_length=100)
    id_num = models.IntegerField("ID Number", unique=True)
    species = models.CharField(max_length=50)
    breed = models.CharField(max_length=50)

    ## Weight is CharField so that "pounds" or "kilograms" can be appended
    weight = models.CharField(max_length=25)
    
    gender = models.CharField(
        max_length=6, 
        choices=(
            ("Male", "Male"), 
            ("Female", "Female")
        )
    )
    
    intake_date = models.DateField("Intake Date")
    
    estimated_age = models.IntegerField("Estimated Age (Years)", default=0)
    estimated_age_months = models.IntegerField("Estimated Age (Months)", default=0)

    image = models.FileField(upload_to="uploads/%Y/%m/", default="")
    notes = models.TextField(blank=True)

    visible_on_website = models.BooleanField("Display on website?", default=True)

    def __str__(self):
        return self.name

'''
This model is to hold extra details for 
animals which might be included in the listing.
'''

class AnimalDetail(models.Model):
    animal = models.OneToOneField(Animal, on_delete=models.CASCADE)
    pregnant = models.BooleanField("Pregnant?")
    microchips = models.BooleanField("Microchipped?")
    good_with_people = models.BooleanField("Good with people?")
    good_with_same_species = models.BooleanField("Good with others of the same species?")
    bite_history = models.BooleanField("Bite history?")
    surrendered_by_owner = models.BooleanField("Surrendered by owner?")
    housebroken = models.BooleanField("Housebroken?")

    reason_for_surrender = models.TextField(
       "If surrendered by owner, why? (Optional)", 
        blank=True
    )
        
    condition_of_teeth = models.TextField(
        "Condition of teeth (Optional)", 
        blank=True
    )
    
    condition_of_skin = models.TextField(
        "Obvious issues or abnormalities? (Optional)", 
        blank=True
    )

    def __str__(self):
        return self.animal.name + ": Details"
    
'''
Separate model for the image of the animal;
This is so that there can be more than one image listed
for any given animal, if necessary.
'''

class Picture(models.Model):
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="uploads/%Y/%m/")
    image_desc = models.CharField(max_length=100)

    def __str__(self):
        return self.animal.name + ": " + self.image_desc
    

apps/listing/forms.py
## Zander B. Wells <zbwells@protonmail.com>
## Part of the Wise Animal Shelter Management System Project.
##
## Released under the terms of the MIT License.
## See LICENSE for details.

from django import forms

## Making forms using Django's form generator, to be consistent with the admin page.
## At least to some extent.

## May need to edit this page depending on client input...
## Since the options are hard-coded for now.

class FilterForm(forms.Form):
    order = forms.ChoiceField( 
        label = "Sort by",
        choices = (
            ("intake_date", "Intake Date"),
            ("name", "Name"), 
            ("estimated_age", "Age"),
            ("gender", "Gender"),
            ("species", "Species"),
            ("breed", "Breed"),
            ("weight", "Weight"),
        )
    )

    # Part of the form to ask the user what ages of animals they would like to see
    filter_by_age = forms.ChoiceField(
        label = "Filter by Age",
        choices = (
            ("any-age", "Any"),
            ("zero-to-two-months", "0 - 2 Months"),
            ("three-to-six-months", "3 - 6 Months"),
            ("seven-to-eleven-months", "7 - 11 Months"),
            ("one-to-two-years", "1 - 2 Years"),
            ("two-or-more-years", "2 or more Years"),
            ("three-or-more-years", "3 or more Years"),
        )
    )

    # Same as previous, but for species; currently only dogs and cats
    filter_by_species = forms.ChoiceField(
        label = "Filter by Species",
        choices = (
            ("any-species", "Any"),
            ("dog", "Dogs"),
            ("cat", "Cats"),
        )
    )
           
    

apps/listing/views.py
## Zander B. Wells <zbwells@protonmail.com>
## Part of the Wise Animal Shelter Management System Project.
##
## Released under the terms of the MIT License.
## See LICENSE for details.


from django.shortcuts import render
from django.views import generic
from django.http import HttpResponse
from django.core.exceptions import FieldError, ValidationError

from .models import *
from .forms import *

## Generic view for the index/animal listing
class IndexView(generic.ListView):
    model = Animal
    template_name = "listing/index.html"

    # Sorts and filters out the list of Animals before sending it to the templates.
    # Done via GET parameters (shown in URL, user can bookmark or share page if desired)
    def get_queryset(self):

        # Default parameters for filtering and ordering the animals
        default = Animal.objects.filter(
            ["visible_on_website", True]
        ).order_by("intake_date")
        
        try:
            filter_by_age = self.request.GET.get(
                "filter_by_age",
                "any-age"
            )

            filter_by_species = self.request.GET.get(
                "filter_by_species",
                "any-species"
            )
            
            order = self.request.GET.get("order", "intake_date")
            
            # Handle age order case
            if order == "estimated_age":
                order = ["estimated_age", "estimated_age_months"]
            
            queries = []
            queries.append(["visible_on_website", True])

            # Handle the age filter's special cases (so, all cases)
            # These correlate to the options specified in forms.py
            if filter_by_age == "any-age":
                pass
                
            elif filter_by_age == "two-or-more-years":
                queries.append(["estimated_age__gt", "1"])

            elif filter_by_age == "three-or-more-years":
                queries.append(["estimated_age__gt", "2"])
                    
            elif filter_by_age == "zero-to-two-months":
                queries.append([
                    "estimated_age_months__in", 
                    ['0', '1', '2']
                ])
                
                queries.append(["estimated_age__lt", '1'])

            elif filter_by_age == "three-to-six-months":
                queries.append([
                    "estimated_age_months__in",
                    ['3', '4', '5', '6']
                ])

                queries.append(["estimated_age__lt", '1'])
                
            elif filter_by_age == "seven-to-eleven-months":
                queries.append([
                    "estimated_age_months__in",
                    ['7', '8', '9', '10', '11']
                ])

                queries.append(["estimated_age__lt", '1'])

            elif filter_by_age == "one-to-two-years":
                queries.append(["estimated_age__in", ['1', '2']])

            # Deal with cases for species filtering
            # Same as before, look at forms.py for options to handle
            if filter_by_species == "any-species":
                pass
            else:
                queries.append(["species__in", 
                    [
                        filter_by_species, 
                        filter_by_species.capitalize(),
                        filter_by_species.upper(),
                    ]
                ])
                
            queryset = Animal.objects

            # Apply all filters
            for lst in queries:
                queryset = queryset.filter(lst)

            # Apply ordering/sorting
            # If ordering by more than one thing, use starred expression
            if isinstance(order, list):
                queryset = queryset.order_by(*order)
            elif isinstance(order, str):
                queryset = queryset.order_by(order)
            

        # If the GET request is malformed, fall back on a default listing setup        
        except (FieldError, ValidationError, ValueError):
            return default

        return queryset

    # Adds our filter form from forms.py
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter_form"] = FilterForm(self.request.GET or None)
            
        context["order"] = str(self.request.GET.get("order")).replace("_", " ")
        
        age_filter = str(self.request.GET.get("filter_by_age"))
        context["age_filter"] = age_filter.replace("-", " ")

        species_filter = str(self.request.GET.get("filter_by_species"))
        context["species_filter"] = species_filter
        
        return context
        

class DetailView(generic.DetailView):
    model = Animal
    template_name = "listing/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        if context["animal"].visible_on_website == False:
            del context["animal"]

        return context

# Inherits from the DetailView we've defined
class ExtraView(DetailView):
    template_name = "listing/extra.html"

apps/listing/templates/listing/detail.html
<!-- Page generated from a template designed by the Wise Animal Shelter Project. -->
<!-- Any JavaScript in this document is released under the terms of the MIT License. -->

<!-- Template for viewing information on a particular animal. -->

{% extends "base.html" %}

{% block title %}
Animal Shelter - 
{% if animal %}
	{{ animal.name }}
{% else %}
	Error
{% endif %}
{% endblock %}

{% block content %}
<br><div class="name"><b>{{ animal.name }}</b></div><br>
<main class="clearfix innerbox listingtext">
{% if animal %}

	<!-- Right aligned image of animal -->

	<img class="floating fade-in" src="{{ animal.image.url }}"/>

	<!-- Animal description -->
	<p>{{ animal.notes }}</p>

	<br>
	<p><b>ID Number:</b> 	{{ animal.id_num  		}}</p>
	<p><b>Species:</b>	  	{{ animal.species 		}}</p>
	<p><b>Breed:</b>	  	{{ animal.breed   		}}</p>
	<p><b>Weight:</b>	  	{{ animal.weight  		}}</p>
	<p><b>Gender:</b>	  	{{ animal.gender  		}}</p>
	<p><b>Intake Date:</b>	{{ animal.intake_date 	}}</p>
	
	<p><b>Estimated Age: </b>
	{{ animal.estimated_age }} years and
	{{ animal.estimated_age_months }} months
	</p>

	{% if animal.animaldetail %}
		<p><a href="{% url 'extra' animal.id %}">
		More Information
		</a></p>
	{% endif %}

{% else %}
	<h2>Animal's details are unviewable.</h2>
	<p>Sorry.</p>
{% endif %}

<br/>
</main>
{% endblock %}

apps/listing/templates/listing/extra.html
<!-- Page generated from a template designed by the Wise Animal Shelter Project. -->
<!-- Any JavaScript in this document is released under the terms of the MIT License. -->

<!-- Template for viewing more information. -->
{% extends "base.html" %}

{% block title %}
Animal Shelter - 
{% if animal.name %}
	{{ animal.name }} - More Information
{% else %}
	Error
{% endif %}
{% endblock %}

{% block content %}
<br><div class="name"><b>{{ animal.name }}</b></div><br>
<main class="innerbox clearfix">
{% if animal %}
	<!-- Right aligned image of animal -->
	{% if animal.picture_set %}
		{% for picture in animal.picture_set.all %}
			<img class="floating fade-in" src="{{ picture.image.url }}"/>
		{% endfor %}
	{% endif %}

	<h2>More Information</h2>

	<!-- List of boolean conditions related to the animal -->
	<ul>
	{% if animal.animaldetail.pregnant %} 
		<li>Is pregnant</li> 
	{% endif %}

	{% if animal.animaldetail.microchips %} 
		<li>Is microchipped</li> 
	{% endif %}

	{% if animal.animaldetail.good_with_people %} 
		<li>Is good with people</li> 
	{% endif %}

	{% if animal.animaldetail.good_with_same_species %} 
		<li>Is good with other {{animal.species}}s</li> 
	{% endif %}

	{% if animal.animaldetail.bite_history %}
		<li>Has a history of biting</li>
	{% endif %}

	{% if animal.animaldetail.surrendered_by_owner %}
		<li>Was surrendered by owner</li>
	{% endif %}

	{% if animal.animaldetail.housebroken %}
		<li>Is housebroken</li>
	{% endif %}
	</ul>

	{% if animal.animaldetail.reason_for_surrender %}
		<p><b>Reason for surrender: </b></p>
		<p>{{animal.animaldetail.reason_for_surrender}}</p>
		<br/>
	{% endif %}

	{% if animal.animaldetail.condition_of_teeth %}
		<p><b>Condition of teeth: </b></p>
		<p>{{animal.animaldetail.condition_of_teeth}}</p>
		<br/>
	{% endif %}

	{% if animal.animaldetail.condition_of_skin %}
		<p><b>Other conditions, such as skin conditions: </b></p>
		<p>{{animal.animaldetail.condition_of_skin}}</p>
		<br/>
	{% endif %}
{% else %}
	<h2>Animal's extra details are unviewable.</h2>
	<p>Sorry.</p>
{% endif %}
<br/>
</main>
{% endblock %}

apps/listing/templates/listing/index.html
<!-- Page generated from a template designed by the Wise Animal Shelter Project. -->
<!-- Any JavaScript in this document is released under the terms of the MIT License. -->
  
<!-- Template for the animal listing main page. -->
<!-- If there are any animals in the database, loop through them and link to them. -->

{% extends "base.html" %}

{% block title %}
Animal Listing
{% endblock %}

{% block content %}
<!-- JavaScript to allow for interacting 
with the filter/sorting interface -->
<script>
// Toggle whether elements are shown or hidden
function toggleElements() {
	for (id of arguments) {
		let elem = document.getElementById(id);
		
		if (elem.style.display != "none") {
			elem.style.display = "none";	
		} else {
			elem.style.display = "block";
		}
	}
}

// Use context to tell if filters have been used, if so, toggle automatically
function autoToggle() {
	if ("{{ order }}" != "None") {
		toggleElements("showtext", "hiddentext");
	}
}
</script>

<main>
<style onload="autoToggle()"></style>
<div class="jumbotron name"><b>Animal Listing</b></div><br/>
<div class="innerbox listingtext">
    <br>
    <span id="showtext">
    <a href="#" onclick="toggleElements('showtext', 'hiddentext'); return false;">
    <small class="innerinnerbox">Show Filters</small>
    </a>
    </span>
    <span id="hiddentext" style="display: none;">
    <a href="#" onclick="toggleElements('showtext', 'hiddentext'); return false;">
    <small class="innerinnerbox">Hide Filters</small>
    <br/><br/>
    </a>

    <!-- Filter form goes here -->
    <form method="get" action="." class="innerinnerbox fade-in">
    {% if order != "None" %}
	    <small><a href="{% url 'index' %}">Reset Filters</a></small>
    {% endif %}
    
    <table>
    {{ filter_form.as_table }}
    <tr><th></th><td><input type="submit" value="Submit"></td></tr>
    </table>
    </form>
    <!-- End of filter form -->

    </span>

    {% if animal_list %}
    <div class="cols listingentry">
	    <!-- Loop through every animal in the list and provide link to details page -->
	    {% for animal in animal_list %}
	    <div>
		    <br/>
		    <a href="{% url 'detail' animal.id %}">
			    {% if animal.name %}
				    <h3>{{ animal.name }}</h3>
			    {% else %}
				    <h3>{{ animal.species }}</h3>
			    {% endif %} 
		    </a>
	    
		    <p>
		    {% if animal.breed %}
			    {{ animal.breed }}
		    {% endif %}
		    </p>
		    <p>
		    {% if animal.estimated_age != 0 %}
			    {{ animal.estimated_age }} years and 
		    {% endif %}  
		    {{ animal.estimated_age_months }} months
		    </p>
		    <a href="{% url 'detail' animal.id %}">
			    <img class="smaller fade-in" src="{{ animal.image.url }}"/>
		    <br/>
	    </div>
	    {% endfor %}
    </div>
</div>

{% else %}
	<p>No animals found.</p>
{% endif %}
</main>

{% endblock %}